vich_uploader:
    db_driver: orm
    mappings:
        before_after_photo:
            uri_prefix: /uploads/before_after
            upload_destination: '%kernel.project_dir%/public/uploads/before_after'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        photo:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        service:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
